#!name=BoxJs
#!desc=[🚀SR] http://boxjs.com
#!author=ChavyLeung
#!icon=https://raw.githubusercontent.com/chavyleung/scripts/master/box/icons/BoxJs.png
#!category=『 🛠️ Amplify Nexus › 增幅枢纽 』
#!homepage=https://docs.boxjs.app/

[General]
bypass-system = true
ipv6 = true
prefer-ipv6 = true
hijack-dns = *:53
dns-direct-fallback-proxy = false

[Script]
Rewrite: BoxJs = type=http-request,pattern=^https?:\/\/(.+\.)?boxjs\.(com|net),script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js, requires-body=true, timeout=120

[MITM]
hostname = boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net, -github.com, -api.github.com, -*.githubusercontent.com
