# name:  iRingo: 📰 News
# category: 『 🛠️ Amplify Nexus › 增幅枢纽 』
# desc: [🚀SR] 1.自定义解锁News的地区\n2.Coming Soon…
# openUrl: http://boxjs.com/#/app/iRingo.News
# author: VirgilClyne[https://github.com/VirgilClyne]
# homepage: https://NSRingo.github.io/guide/apple-news
# icon: https://developer.apple.com/assets/elements/icons/news/news-128x128.png
# date: 2024-12-10 04:32:39
# version: 3.2.1
# arguments: Proxy:🇺🇸美国,CountryCode:"US",NewsPlusUser:true,LogLevel:"WARN"
# arguments-desc: Proxy: News 分流规则使用的策略名\nCountryCode: 国家或地区代码\n    ├ AUTO: 🇺🇳自动（跟随地区检测结果）\n    ├ CN: 🇨🇳中国大陆\n    ├ HK: 🇭🇰香港\n    ├ TW: 🇹🇼台湾\n    ├ SG: 🇸🇬新加坡\n    ├ US: 🇺🇸美国\n    ├ JP: 🇯🇵日本\n    ├ AU: 🇦🇺澳大利亚\n    ├ GB: 🇬🇧英国\n    ├ KR: 🇰🇷韩国\n    ├ CA: 🇨🇦加拿大\n    └ IE: 🇮🇪爱尔兰\n不同国家或地区提供的内容或有差别。\n\nNewsPlusUser: [搜索]显示News+内容\n是否显示News+搜索结果。\n\nLogLevel: [调试] 日志等级\n    ├ OFF: 关闭\n    ├ ERROR: ❌ 错误\n    ├ WARN: ⚠️ 警告\n    ├ INFO: ℹ️ 信息\n    ├ DEBUG: 🅱️ 调试\n    └ ALL: 全部\n选择脚本日志的输出等级，低于所选等级的日志将全部输出。\n

[Rule]
# ☁️ iCloud
DOMAIN,gateway.icloud.com,{{{Proxy}}}
# 📰 News
# --- Expanded from https://github.com/NSRingo/News/releases/download/v3.2.1/News.list ---
DOMAIN,news-edge.apple.com,{{{Proxy}}}
DOMAIN,news-events.apple.com,{{{Proxy}}}
DOMAIN,apple.comscoreresearch.com,{{{Proxy}}}
# --- End expansion ---

[Script]
📰 News.v1.configs.request = type=http-request, pattern=^https?:\/\/news(-todayconfig)?-edge\.apple\.com\/v1\/configs, requires-body=1, script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/github_com_2d9075_request.bundle.js, argument=CountryCode="{{{CountryCode}}}"&NewsPlusUser="{{{NewsPlusUser}}}"&LogLevel="{{{LogLevel}}}"
📰 News.analyticseventsv2.async.request = type=http-request, pattern=^https?:\/\/news(-sports)?-events\.apple\.com\/analyticseventsv2\/async, requires-body=1, script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/github_com_2d9075_request.bundle.js, argument=CountryCode="{{{CountryCode}}}"&NewsPlusUser="{{{NewsPlusUser}}}"&LogLevel="{{{LogLevel}}}"
📰 News.v1.search.request = type=http-request, pattern=^https?:\/\/news-client-search\.apple\.com\/v1\/search, requires-body=0, script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/github_com_2d9075_request.bundle.js, argument=CountryCode="{{{CountryCode}}}"&NewsPlusUser="{{{NewsPlusUser}}}"&LogLevel="{{{LogLevel}}}"

[MITM]
hostname = news-edge.apple.com, news-todayconfig-edge.apple.com, news-events.apple.com, news-sports-events.apple.com, news-client.apple.com, news-client-search.apple.com
