# category: 『 🛠️ Amplify Nexus › 增幅枢纽 』
# name:  iRingo: 📺 TV app
# desc: [🚀SR] 全面自定义「TV app」功能
# openUrl: http://boxjs.com/#/app/iRingo.TV
# author: VirgilClyne[https://github.com/VirgilClyne]
# homepage: https://NSRingo.github.io/guide/apple-tv
# icon: https://developer.apple.com/assets/elements/icons/apple-tv/apple-tv-128x128.png
# date: 2025-04-17 03:19:05
# version: 3.4.4
# arguments: ThirdParty:false,isWorkaroundSSLPinning:true,LogLevel:"WARN"
# arguments-desc: ThirdParty: 启用第三方 App 与 TV app 关联功能
是否将桌面版/macOS版/app版等平台的 TV app 转换至 iPad 版，以启用第三方 App 与 TV app 关联功能(如: Disney+, Prime Video 等)。

isWorkaroundSSLPinning: 启用绕过 SSL 证书固定校验
是否绕过播放列表所使用域名的证书固定校验功能，从而恢复对DualSubs的双语字幕支持。

LogLevel: [调试] 日志等级
    ├ OFF: 🔴 关闭
    ├ ERROR: ❌ 错误
    ├ WARN: ⚠️ 警告
    ├ INFO: ℹ️ 信息
    ├ DEBUG: 🅱️ 调试
    └ ALL: 全部
选择脚本日志的输出等级，低于所选等级的日志将全部输出。


[Rule]
DOMAIN,known-issues.apple.com,REJECT

[URL Rewrite]
^https?:\/\/play-cdn\.itunes\.apple\.com https://play.itunes.apple.com header
^https?:\/\/play-edge-cdn\.itunes\.apple\.com https://play-edge.itunes.apple.com header

[Script]
📺 TV.uts.request = type=http-request, pattern=^https?:\/\/uts-api\.itunes\.apple\.com\/uts\/(v1|v2|v3)\/, requires-body=1, script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/github_com_b9f352_request.bundle.js, argument=ThirdParty="{{{ThirdParty}}}"&isWorkaroundSSLPinning="{{{isWorkaroundSSLPinning}}}"&LogLevel="{{{LogLevel}}}"
📺 TV.uts.response = type=http-response, pattern=^https?:\/\/uts-api\.itunes\.apple\.com\/uts\/(v1|v2|v3)\/, requires-body=1, script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/github_com_43a014_response.bundle.js, argument=ThirdParty="{{{ThirdParty}}}"&isWorkaroundSSLPinning="{{{isWorkaroundSSLPinning}}}"&LogLevel="{{{LogLevel}}}"
📺 TV.umc.request = type=http-request, pattern=^https?:\/\/umc-tempo-api\.apple\.com\/(v1|v2|v3)\/, requires-body=1, script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/github_com_b9f352_request.bundle.js, argument=

[MITM]
hostname = uts-api.itunes.apple.com, umc-tempo-api.apple.com, play-cdn.itunes.apple.com, play-edge-cdn.itunes.apple.com, -github.com, -api.github.com, -*.githubusercontent.com
