# category: 『 🛠️ Amplify Nexus › 增幅枢纽 』
# name: Reddit 增强合集 (翻译 + 广告 + NSFW)
# desc: [🚀SR] Reddit 功能增强：自动翻译 + 去广告 + NSFW 解锁 (基于 JQ 引擎)
# author: RavelloH, ScriptHub

[General]
bypass-system = true
ipv6 = true
prefer-ipv6 = true
hijack-dns = *:53
dns-direct-fallback-proxy = false
# [SR不支持,已移除] force-http-engine-hosts = %APPEND% gql.reddit.com, gql-fed.reddit.com

[Script]
# 自动翻译注入
Reddit 自动翻译 = type=http-request, pattern=^https?:\/\/gql(-fed)?\.reddit\.com, script-path=https://gist.github.com/RavelloH/68ed0626dae69a1ce7c8ad6887087ea1/raw/c008127260bc4dcd550fcd98285048cf6176f602/main.js, timeout=30, requires-body=false

[Body Rewrite]
# NSFW 解锁与去广告 (JQ 版)
http-response-jq ^https?:\/\/gql(-fed)?\.reddit\.com 'walk( if type == "object" then (if .is{{{NSFW}}} == true then .is{{{NSFW}}} = false else . end) | (if .is{{{NSFW}}}MediaBlocked == true then .is{{{NSFW}}}MediaBlocked = false else . end) | (if .is{{{NSFW}}}ContentShown == false then .is{{{NSFW}}}ContentShown = true else . end) | (if (.commentsPageAds | type == "array") then (.commentsPageAds = []) else . end) | (if ( (.node | type == "object") and (.node.cells | type == "array") and (.node.cells | any(.__typename? == "AdMetadataCell" or .isAdPost? == true)) ) then empty else . end) | (if (.node | type == "object") and (.node.adPayload | type == "object") then empty else . end) | (if .__typename == "AdPost" then empty else . end) else . end)'

[MITM]
hostname = gql.reddit.com, gql-fed.reddit.com, -github.com, -api.github.com, -*.githubusercontent.com
