#!name=Script Hub: 重写 & 规则集转换
#!desc=[🚀SR] https://script.hub
#!author=@小白脸 @xream @keywos @ckyb
#!category=『 🛠️ Amplify Nexus › 增幅枢纽 』
#!arguments=Notify:开启通知
#!arguments-desc=Notify:\nScriptHub通知设置, 可选 开启通知, 关闭通知, 跟随链接

[General]
bypass-system = true
ipv6 = true
prefer-ipv6 = true
hijack-dns = *:53
dns-direct-fallback-proxy = false

[Script]
Script Hub: 前端 = type=http-request, pattern=^https?:\/\/script\.hub\/($|edit\/|reload), script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/raw_githubusercontent_com_f59ef7_script-hub.js, timeout=300
Script Hub: 重写转换 = type=http-request, pattern=^https?:\/\/script\.hub\/file\/_start_\/.+type=(?:qx-rewrite|surge-module|loon-plugin|all-module), script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/raw_githubusercontent_com_4fd0f5_Rewrite-Parser.js, timeout=300, argument=Notify={{{Notify}}}
Script Hub: 规则集转换 = type=http-request, pattern=^https?:\/\/script\.hub\/file\/_start_\/.+type=rule-set, script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/raw_githubusercontent_com_0aa101_rule-parser.js, timeout=300, argument=Notify={{{Notify}}}
Script Hub: 脚本转换 = type=http-request, pattern=^https?:\/\/script\.hub\/convert\/, script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/raw_githubusercontent_com_95a370_script-converter.js, timeout=300

[MITM]
hostname = script.hub, *.script.hub, -github.com, -api.github.com, -*.githubusercontent.com
