# category: 『 🛠️ Amplify Nexus › 增幅枢纽 』
# name: 📺 YouTube增强合集
# desc: [🚀SR] 合并YouTube增强+去广告 (自动追随上游更新)\n🎬 Enhance: 画中画/后台播放/字幕翻译\n🛡️ ADBlock: 去广告
# author: Maasea
# icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png
# tag: YouTube, 增强, 去广告
# date: 2025-12-20 03:02:07
# arguments: 屏蔽上传按钮:true,屏蔽选段按钮:true,屏蔽Shorts按钮:false,字幕翻译语言:off,歌词翻译语言:off,启用调试模式:false
# arguments-desc: \n\n[Youtube (Music) Enhance]\n- 屏蔽参数：[true, false] \n- 翻译参数：[语言代码, off] \n\n1. 语言代码遵循 Google Translate Languages Codes, 当填入 off 时关闭翻译\n2. 开启调试模式用于输出更多日志

[Rule]
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data="" status-code=200

[Script]
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?(.*))?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/nowaytouse/script_hub/master/module/scripts/raw_githubusercontent_com_89f8ba_youtube.response.js,argument="{"lyricLang":"{{{歌词翻译语言}}}","captionLang":"{{{字幕翻译语言}}}","blockUpload":{{{屏蔽上传按钮}}},"blockImmersive":{{{屏蔽选段按钮}}},"blockShorts":{{{屏蔽Shorts按钮}}},"debug":{{{启用调试模式}}}}"

[MITM]
hostname = *.googlevideo.com, youtubei.googleapis.com, -github.com, -api.github.com, -*.githubusercontent.com
