"""Canonical repository paths (single source of truth for folder layout)."""

from __future__ import annotations

import os

from hub.common import get_project_root

ROOT = get_project_root()

# Surge amplify_nexus published modules
AMPLIFY_NEXUS_DIR = os.path.join(ROOT, "modules/surge/amplify_nexus")

# Surge / Shadowrocket compiled .list rulesets
LIST_DIR = os.path.join(ROOT, "rulesets/list")
SKK_UPSTREAM_DIR = os.path.join(LIST_DIR, "skk_upstream")
ADBLOCK_LIST = os.path.join(LIST_DIR, "AdBlock.list")
HTTPDNS_HIJACK_LIST = os.path.join(LIST_DIR, "HTTPDNS_Hijack.list")

# PROMAX local module sources (upstream-synced sgmodules)
LOCAL_DIR = os.path.join(ROOT, "modules/source/local")

# Other stable trees
ADBLOCK_DIR = os.path.join(ROOT, "rulesets/AdBlock")
SINGBOX_DIR = os.path.join(ROOT, "rulesets/SingBox")
LOCAL_MODULES_DIR = os.path.join(ROOT, "rulesets/Sources/LocalModules")
MODULES_HELPER_DIR = os.path.join(ROOT, "modules/helper")
MODULES_DATA_JSON = os.path.join(MODULES_HELPER_DIR, "modules_data.json")
SHADOWROCKET_MODULES_JSON = os.path.join(MODULES_HELPER_DIR, "shadowrocket_modules_data.json")
SURGE_MODULE_HELPER_HTML = os.path.join(MODULES_HELPER_DIR, "surge_module_helper.html")
MODULES_COMPATIBILITY_JSON = os.path.join(MODULES_HELPER_DIR, "modules_compatibility.json")

# Published helper page (regenerated by tools/consolidate_modules.py in main_update)
REPO_RAW_PREFIX = "https://raw.githubusercontent.com/nowaytouse/script_hub/master/"
SURGE_MODULE_HELPER_URL = f"{REPO_RAW_PREFIX}modules/helper/surge_module_helper.html"

# Maasea upstream (repo renamed sgmodules → sgmodule)
MAASEA_SGMODULE_BASE = "https://raw.githubusercontent.com/Maasea/sgmodule/master"
YOUTUBE_ENHANCE_URL = f"{MAASEA_SGMODULE_BASE}/YouTube.Enhance.sgmodule"
BILIBILI_HELPER_URL = f"{MAASEA_SGMODULE_BASE}/Bilibili.Helper.sgmodule"

# Raw GitHub URL prefix for published list rulesets
LIST_RAW_PREFIX = f"{REPO_RAW_PREFIX}rulesets/list/"

# Vendored Surge/Shadowrocket scripts (localize_scripts.py)
SCRIPTS_DIR = os.path.join(ROOT, "modules/source/scripts")
SCRIPT_RAW_PREFIX = f"{REPO_RAW_PREFIX}modules/source/scripts/"

# Legacy paths (pre folder restructure) — repair_script_paths.py rewrites these
LEGACY_SCRIPT_RAW_PREFIX = f"{REPO_RAW_PREFIX}modules/scripts/"
LEGACY_LIST_RAW_PREFIX = f"{REPO_RAW_PREFIX}ruleset/Surge(Shadowkroket)/"
