#!name=WeChat增强
#!desc=[🚀SR] WeChat/微信解锁外部链接与小程序优化。
#!author=ld2j[https://github.com/LD2J0618],RuCu6[https://github.com/RuCu6],可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md],VirgilClyne,zZPiglet[https://github.com/zZPiglet],wish[https://github.com/mist-whisper],ZenmoFeiShi[https://github.com/ZenmoFeiShi]
#!category=『 🛠️ Amplify Nexus › 增幅枢纽 』
#!date=2025-07-20 21:12:00
#!arguments=Proxy:DIRECT
#!arguments-desc=Proxy:选择策略组，将微信&WeChat相关域名分流，默认DIRECT。

[Script]
微信外部链接解锁   = type=http-response, pattern=^https\:\/\/(weixin110\.qq|security.wechat)\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi\?, script-path=https://cdn.jsdelivr.net/gh/nowaytouse/script_hub@master/modules/source/scripts/raw_githubusercontent_com_36f4d2_Weixin_external_links_unlock.js, requires-body=true
美团小程序tap优化 = type=http-response, pattern=^https:\/\/web\.meituan\.com\/api\/miniprogram\/tabbar\/all\/query, script-path=https://cdn.jsdelivr.net/gh/nowaytouse/script_hub@master/modules/source/scripts/raw_githubusercontent_com_b02c6b_MeiTuan.js, requires-body=true, timeout=60


[MITM]
hostname = %APPEND% weixin110.qq.com, security.wechat.com, web.meituan.com, npay.meituan.com
