#!name=📺 YouTube增强合集
#!desc=[🚀SR] YouTube 功能增强；广告行由 Rust 拆分后并入 PROMAX
#!author=Maasea
#!icon=https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/YouTube.png
#!category=『 🛠️ Amplify Nexus › 增幅枢纽 』
#!arguments=屏蔽上传按钮:true,屏蔽选段按钮:true,屏蔽Shorts按钮:true,字幕翻译语言:"zh-Hans",启用调试模式:false
#!arguments-desc=- 屏蔽参数：[true, false] \n- 翻译参数：[语言代码, off] \n\n1. 语言代码遵循 Google Translate Languages Codes, 当填入 off 时关闭翻译\n2. 开启调试模式用于输出更多日志
# Upstream module processed by create/processor/merge_bundles.rs
# - Moved: [Rule], [Map Local] and *.googlevideo.com ad handling to PROMAX

[Script]
youtube.response          = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch|log_event|config))(\?(.*))?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://cdn.jsdelivr.net/gh/Maasea/sgmodule@master/Script/Youtube/youtube.response.js,argument="{"captionLang":"{{{字幕翻译语言}}}","blockUpload":{{{屏蔽上传按钮}}},"blockImmersive":{{{屏蔽选段按钮}}},"blockShorts":{{{屏蔽Shorts按钮}}},"debug":{{{启用调试模式}}}}"
youtube.request.log_event = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/log_event,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://cdn.jsdelivr.net/gh/Maasea/sgmodule@master/Script/Youtube/youtube.request.js


[MITM]
hostname = %APPEND% youtubei.googleapis.com
