# Flattened rules for github -> group github
domain-rules /atom.io/ -nameserver github
domain-rules /blob.core.windows.net/ -nameserver github
domain-rules /collector.github.com/ -nameserver github
domain-rules /copilot-telemetry.githubusercontent.com/ -nameserver github
domain-rules /dependabot.com/ -nameserver github
domain-rules /gh.io/ -nameserver github
domain-rules /ghcr.io/ -nameserver github
domain-rules /git.io/ -nameserver github
domain-rules /github/ -nameserver github
domain-rules /github-api.arkoselabs.com/ -nameserver github
domain-rules /github-atom-io-herokuapp-com.freetls.fastly.net/ -nameserver github
domain-rules /github-avatars.oss-cn-hongkong.aliyuncs.com/ -nameserver github
domain-rules /github-cloud.s3.amazonaws.com/ -nameserver github
domain-rules /github.ai/ -nameserver github
domain-rules /github.blog/ -nameserver github
domain-rules /github.com/ -nameserver github
domain-rules /github.community/ -nameserver github
domain-rules /github.dev/ -nameserver github
domain-rules /github.io/ -nameserver github
domain-rules /githubapp.com/ -nameserver github
domain-rules /githubassets.com/ -nameserver github
domain-rules /githubcopilot.com/ -nameserver github
domain-rules /githubhackathon.com/ -nameserver github
domain-rules /githubnext.com/ -nameserver github
domain-rules /githubpreview.dev/ -nameserver github
domain-rules /githubstatus.com/ -nameserver github
domain-rules /githubuniverse.com/ -nameserver github
domain-rules /githubusercontent.com/ -nameserver github
domain-rules /myoctocat.com/ -nameserver github
domain-rules /npm.community/ -nameserver github
domain-rules /npmjs.com/ -nameserver github
domain-rules /npmjs.org/ -nameserver github
domain-rules /octocaptcha.com/ -nameserver github
domain-rules /opensource.guide/ -nameserver github
domain-rules /rawgit.com/ -nameserver github
domain-rules /rawgithub.com/ -nameserver github
domain-rules /repo.new/ -nameserver github
domain-rules /thegithubshop.com/ -nameserver github
