# Flattened rules for tiktok -> group tiktok
domain-rules /byteoversea.com/ -nameserver tiktok
domain-rules /ibytedtos.com/ -nameserver tiktok
domain-rules /muscdn.com/ -nameserver tiktok
domain-rules /musical.ly/ -nameserver tiktok
domain-rules /tiktok/ -nameserver tiktok
domain-rules /tiktok.com/ -nameserver tiktok
domain-rules /tiktokcdn.com/ -nameserver tiktok
domain-rules /tiktokv.com/ -nameserver tiktok
domain-rules /tiktokv.us/ -nameserver tiktok
domain-rules /tiktokw.us/ -nameserver tiktok
