# Flattened rules for tw -> group tw
domain-rules /bahamut.akamaized.net/ -nameserver tw
domain-rules /bahamut.com.tw/ -nameserver tw
domain-rules /chocotv.com.tw/ -nameserver tw
domain-rules /d17lx9ucc6k9fc.cloudfront.net/ -nameserver tw
domain-rules /d3c7rimkq79yfu.cloudfront.net/ -nameserver tw
domain-rules /d3pgb93pk7bvxj.cloudfront.net/ -nameserver tw
domain-rules /d3vm9lcxb6xcm4.cloudfront.net/ -nameserver tw
domain-rules /digicert.com/ -nameserver tw
domain-rules /fetnet.net/ -nameserver tw
domain-rules /friday.tw/ -nameserver tw
domain-rules /gamer.com.tw/ -nameserver tw
domain-rules /gvt1.com/ -nameserver tw
domain-rules /hinet.net/ -nameserver tw
domain-rules /kktv-theater.kk.stream/ -nameserver tw
domain-rules /kktv.com.tw/ -nameserver tw
domain-rules /kktv.me/ -nameserver tw
domain-rules /line-cdn.net/ -nameserver tw
domain-rules /line-scdn.net/ -nameserver tw
domain-rules /linetv.tw/ -nameserver tw
domain-rules /litv.tv/ -nameserver tw
domain-rules /litvfreemobile-hichannel.cdn.hinet.net/ -nameserver tw
domain-rules /theater-kktv.cdn.hinet.net/ -nameserver tw
domain-rules /viblast.com/ -nameserver tw
