# category: 『 🎯 Narrow Pierce › 窄域穿刺 』
# name: 扫描全能王

# desc: [🚀SR] 解锁扫描全能王

# author: NobyDa

# icon: https://raw.githubusercontent.com/deezertidal/private/main/icons/cs.png



[MITM]

hostname = ap*.intsig.net, -github.com, -api.github.com, -*.githubusercontent.com



[Script]

扫描全能王=type=http-response,pattern=https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\?,requires-body=1, script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/CamScanner.js

